id: P946E4CC8
initial_creation_type: input
source_metadata:
  Title: Vijnaptimatrasiddhi-prakaranam-dvayam
  Editor: Tripathi, Ram Shankar
  Publisher: Sampurnananda Sanskrit University
  Place of Publication: Varanasi, India
  Year: '1992'
  Viṃśatikā vijñaptimātratāsiddhiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:57:08.148725'
last_modified_at: '2022-03-08T16:57:08.148732'
